# Analyzing income
The purpose of this notebook is to investigate the various ways we can measure income from surveys B and C

In [7]:
import pandas as pd
import matplotlib.pyplot as plt 
import numpy as np
from zipfile import ZipFile
import os
import seaborn as sns
from autoviz import data_cleaning_suggestions

pd.options.mode.chained_assignment = None

In [9]:
# specifiy location of data
df = pd.read_csv("/home/rthoms/ocean_dep/sur_B/capture_table_clean.csv")
df = df[['id','ccp', 'gender', 'fish_pract', 'pract_cat', 
        'focal_resource','prop_cap_hot', 'prop_cap_cold', 'days_hot', 'days_cold',
        'cap_daily_hot', 'cap_daily_cold', 'cap_monthly_hot',
        'cap_monthly_cold', 'cap_income_hot', 'cap_income_cold',
        'val_trade_hot', 'val_trade_cold', 'activity_income_hot',
        'activity_income_cold', 'income_fr_hot', 'income_fr_cold',
        'tot_income_hot', 'tot_income_cold', 'prop_income_hot',
        'prop_income_cold',]]

In [10]:
print(f"There are {len(df)} rows and {len(df.columns)} columns in dataframe.")

There are 269 rows and 26 columns in dataframe.

In [11]:
data_cleaning_suggestions(df)

,Data Type,Missing Values%,Unique Values%,Minimum Value,Maximum Value,DQ Issue
id,object,0.000000,35,NaN,NaN,50 rare categories: Too many to list. Group them into a single category or drop the categories.
ccp,object,0.000000,4,NaN,NaN,No issue
gender,object,0.000000,0,NaN,NaN,No issue
fish_pract,object,0.000000,2,NaN,NaN,1 rare categories: ['basket_trap']. Group them into a single category or drop the categories.
pract_cat,object,0.000000,1,NaN,NaN,No issue
focal_resource,int64,0.000000,8,1.000000,78.0,No issue
prop_cap_hot,float64,0.000000,NA,0.033333,1.0,has 26 outliers greater than upper bound (0.63) or lower than lower bound(-0.17). Cap them or remove them.
prop_cap_cold,float64,0.000000,NA,0.000000,1.0,has 20 outliers greater than upper bound (0.68) or lower than lower bound(-0.25). Cap them or remove them.
days_hot,float64,0.000000,NA,0.000000,15.0,has 24 outliers greater than upper bound (13.00) or lower than lower bound(-3.00). Cap them or remove them.
days_cold,float64,7.806691,NA,0.000000,15.0,"21 missing values. Impute them with mean, median, mode, or a constant value such as 123., has 16 outliers greater than upper bound (14.50) or lower than lower bound(-5.50). Cap them or remove them."
cap_daily_hot,float64,2.602230,NA,0.250000,125.0,"7 missing values. Impute them with mean, median, mode, or a constant value such as 123., has 15 outliers greater than upper bound (27.33) or lower than lower bound(-13.55). Cap them or remove them."
cap_daily_cold,float64,11.524164,NA,0.000000,75.0,"31 missing values. Impute them with mean, median, mode, or a constant value such as 123., has 25 outliers greater than upper bound (13.50) or lower than lower bound(-6.50). Cap them or remove them."
cap_monthly_hot,float64,5.204461,NA,0.000000,1250.0,"14 missing values. Impute them with mean, median, mode, or a constant value such as 123., has 23 outliers greater than upper bound (223.12) or lower than lower bound(-115.88). Cap them or remove them., has a high correlation with ['cap_daily_hot']. Consider dropping one of them."
cap_monthly_cold,float64,13.382900,NA,0.000000,576.0,"36 missing values. Impute them with mean, median, mode, or a constant value such as 123., has 30 outliers greater than upper bound (138.30) or lower than lower bound(-70.50). Cap them or remove them."
cap_income_hot,float64,0.000000,NA,0.000000,50400.0,has 30 outliers greater than upper bound (10900.00) or lower than lower bound(-6166.67). Cap them or remove them.
cap_income_cold,float64,0.000000,NA,0.000000,21436.8,has 34 outliers greater than upper bound (7280.00) or lower than lower bound(-4368.00). Cap them or remove them.
val_trade_hot,float64,0.000000,NA,0.000000,18400.0,has 50 outliers greater than upper bound (0.00) or lower than lower bound(0.00). Cap them or remove them.
val_trade_cold,float64,0.000000,NA,0.000000,8640.0,has 42 outliers greater than upper bound (0.00) or lower than lower bound(0.00). Cap them or remove them.
activity_income_hot,float64,0.000000,NA,0.000000,38000.0,has 65 outliers greater than upper bound (0.00) or lower than lower bound(0.00). Cap them or remove them.
activity_income_cold,float64,0.000000,NA,0.000000,38000.0,"has 66 outliers greater than upper bound (0.00) or lower than lower bound(0.00). Cap them or remove them., has a high correlation with ['activity_income_hot']. Consider dropping one of them."
income_fr_hot,float64,0.000000,NA,0.000000,50400.0,"has 31 outliers greater than upper bound (12140.00) or lower than lower bound(-6793.33). Cap them or remove them., has a high correlation with ['cap_income_hot']. Consider dropping one of them."
income_fr_cold,float64,0.000000,NA,0.000000,27840.0,"has 28 outliers greater than upper bound (9000.00) or lower than lower bound(-5400.00). Cap them or remove them., has a high correlation with ['cap_income_cold']. Consider dropping one of them."
tot_income_hot,float64,0.000000,NA,0.000000,90416.0,has 11 outliers greater than upper bound (64155.40) or lower than lower bound(-32925.67). Cap them or remove them.
tot_income_cold,float64,0.000000,NA,0.000000,72352.0,has 25 outliers greater than upper bound (37440.00) or lower than lower bound(-20160.00). Cap them or remove them.
prop_income_hot,float64,0.000000,NA,0.000000,1.0,No issue
prop_income_cold,float64,0.000000,NA,0.000000,1.0,No issue